const ACTION_TYPES = {
    CART_DATA_LOADING: 'CART_DATA_LOADING',
    GET_CART_DATA: 'GET_CART_DATA',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART'
}

export default ACTION_TYPES;