const ACTION_TYPES = {
    PRODUCTCUSTOMIZEPROPS_LOADING: 'PRODUCTCUSTOMIZEPROPS_LOADING',
    GET_PRODUCTCUSTOMIZEPROPS: 'GET_PRODUCTCUSTOMIZEPROPS',
    PURCHASE_PRODUCT: 'PURCHASE_PRODUCT',
    PURCHASE_PRODUCT_HISTORY: 'PURCHASE_PRODUCT_HISTORY',
    CHECKOUT_PRODUCT: 'CHECKOUT_PRODUCT'
}

export default ACTION_TYPES;