const ACTION_TYPES = {
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_USER: 'GET_USER',
    DELETE_USER: 'DELETE_USER',
    UPDATE_USER: 'UPDATE_USER',
    USER_LOADING: 'USER_LOADING',
};
export default ACTION_TYPES;