const ACTION_TYPES = {
    USER_LOGIN: 'USER_LOGIN',
    USER_REGISTRATION: 'USER_REGISTRATION',
    GET_USER_CREDENTIALS: 'GET_USER_CREDENTIALS',
    BILLING_DETAILS: 'BILLING_DETAILS'
};
export default ACTION_TYPES;